# Generated by Django 4.2.20 on 2025-04-16 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import main.order.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('address', models.CharField(blank=True, max_length=350)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zip_code_or_postal_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='jumbotron/')),
                ('order', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=main.order.models.order_id_generator, max_length=11, unique=True)),
                ('status', models.CharField(choices=[('C', 'Cancelled'), ('F', 'Fulfilled'), ('P', 'Processing'), ('N', 'New')], default='N', max_length=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('stripe_api_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255)),
                ('coin_base_api_key', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('trending', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_to', models.CharField(choices=[('address', 'My address'), ('global', 'Global')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
            options={
                'verbose_name_plural': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('max_items', models.PositiveSmallIntegerField(default=10)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ManyToManyField(blank=True, to='main.store')),
            ],
            options={
                'verbose_name': 'Store Category',
                'verbose_name_plural': 'Store Categories',
                'db_table': 'page',
                'ordering': ('-id', 'created_date'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.store')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('step', models.IntegerField()),
                ('image', models.ImageField(upload_to='shop/howto')),
                ('video_url', models.URLField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='how_to_store', to='main.store')),
            ],
            options={
                'ordering': ('step',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('image', models.URLField()),
                ('title', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('original_price', models.CharField(blank=True, max_length=20)),
                ('sales_price', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('shipping_fee', models.IntegerField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('approve', 'Approve'), ('disable', 'Disable')], default='pending', max_length=10)),
                ('shipping', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
