version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - .:/django
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sagefahd
    image: app:django
    container_name: postgres1_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=Sagefahd
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



 